# -*- coding: utf-8 -*-
from __future__ import annotations

from relay_teams.interfaces.server.routers import (
    artifacts_router,
    audit,
    auto_harness,
    automation,
    commands,
    feishu_gateway,
    gateway,
    guardrails_router,
    logs,
    mcp,
    memories,
    observability,
    prompts,
    roles,
    runs,
    session_media,
    sessions,
    speech,
    system,
    tasks,
    triggers,
    workspaces,
)

__all__ = [
    "artifacts_router",
    "audit",
    "auto_harness",
    "automation",
    "commands",
    "feishu_gateway",
    "gateway",
    "guardrails_router",
    "logs",
    "mcp",
    "memories",
    "observability",
    "prompts",
    "roles",
    "runs",
    "session_media",
    "sessions",
    "speech",
    "system",
    "tasks",
    "triggers",
    "workspaces",
]
