# -*- coding: utf-8 -*-
from __future__ import annotations

from relay_teams.env.environment_variable_models import (
    EnvironmentVariableCatalog,
    EnvironmentVariableRecord,
    EnvironmentVariableSaveRequest,
    EnvironmentVariableScope,
    EnvironmentVariableValueKind,
)
from relay_teams.env.environment_variable_service import EnvironmentVariableService
from relay_teams.env.runtime_env import (
    get_app_env_file_path,
    get_env_var,
    get_project_env_file_path,
    get_user_env_file_path,
    load_env_file,
    load_merged_env_vars,
    sync_app_env_to_process_env,
)
from relay_teams.env.clawhub_cli import (
    CLAWHUB_PREFERRED_NPM_REGISTRY,
    CLAWHUB_NPM_PACKAGE_NAME,
    ClawHubCliInstallResult,
    clear_clawhub_path_cache,
    install_clawhub_via_npm,
    resolve_existing_clawhub_path,
)
from relay_teams.env.clawhub_config_models import ClawHubConfig
from relay_teams.env.clawhub_config_service import ClawHubConfigService
from relay_teams.env.clawhub_env import (
    CLAWHUB_REGISTRY_ENV_KEY,
    CLAWHUB_SITE_ENV_KEY,
    CLAWHUB_TOKEN_ENV_KEY,
    DEFAULT_CLAWHUB_CN_REGISTRY,
    DEFAULT_CLAWHUB_CN_SITE,
    build_clawhub_cli_env,
    build_clawhub_subprocess_env,
    clawhub_env_keys,
    normalize_clawhub_registry,
    normalize_clawhub_site,
    normalize_clawhub_token,
    resolve_clawhub_registry_from_env,
    resolve_default_clawhub_registry,
    resolve_clawhub_site_from_env,
    resolve_default_clawhub_site,
    resolve_clawhub_token_from_env,
    strip_clawhub_endpoint_overrides,
)
from relay_teams.env.proxy_env import (
    ProxyEnvConfig,
    ProxyEnvInput,
    apply_proxy_env_to_process_env,
    build_subprocess_env,
    extract_proxy_env_vars,
    host_matches_no_proxy,
    load_proxy_env_config,
    mask_proxy_url,
    parse_no_proxy_rules,
    proxy_applies_to_url,
    resolve_proxy_env_config,
    sync_proxy_env_to_process_env,
)
from relay_teams.env.github_config_models import GitHubConfig
from relay_teams.env.github_config_service import GitHubConfigService
from relay_teams.env.github_connectivity import (
    GitHubConnectivityProbeDiagnostics,
    GitHubConnectivityProbeRequest,
    GitHubConnectivityProbeResult,
    GitHubConnectivityProbeService,
)
from relay_teams.env.github_env import (
    GH_NO_EXTENSION_UPDATE_NOTIFIER_ENV_KEY,
    GH_NO_UPDATE_NOTIFIER_ENV_KEY,
    GH_PROMPT_DISABLED_ENV_KEY,
    GITHUB_TOKEN_ENV_KEY,
    GH_TOKEN_ENV_KEY,
    build_github_cli_env,
    github_env_keys,
    normalize_github_token,
    resolve_github_token_from_env,
)
from relay_teams.env.proxy_config_service import ProxyConfigService
from relay_teams.env.web_config_models import (
    WebConfig,
    WebFallbackProvider,
    WebProvider,
)
from relay_teams.env.web_config_service import WebConfigService
from relay_teams.env.web_connectivity import (
    WebConnectivityProbeDiagnostics,
    WebConnectivityProbeRequest,
    WebConnectivityProbeResult,
    WebConnectivityProbeService,
)

__all__ = [
    "EnvironmentVariableCatalog",
    "EnvironmentVariableRecord",
    "EnvironmentVariableSaveRequest",
    "EnvironmentVariableScope",
    "EnvironmentVariableService",
    "EnvironmentVariableValueKind",
    "CLAWHUB_NPM_PACKAGE_NAME",
    "CLAWHUB_PREFERRED_NPM_REGISTRY",
    "CLAWHUB_REGISTRY_ENV_KEY",
    "CLAWHUB_SITE_ENV_KEY",
    "CLAWHUB_TOKEN_ENV_KEY",
    "ClawHubCliInstallResult",
    "ClawHubConfig",
    "ClawHubConfigService",
    "GitHubConfig",
    "GitHubConfigService",
    "GitHubConnectivityProbeDiagnostics",
    "GitHubConnectivityProbeRequest",
    "GitHubConnectivityProbeResult",
    "GitHubConnectivityProbeService",
    "GITHUB_TOKEN_ENV_KEY",
    "GH_NO_EXTENSION_UPDATE_NOTIFIER_ENV_KEY",
    "GH_NO_UPDATE_NOTIFIER_ENV_KEY",
    "GH_PROMPT_DISABLED_ENV_KEY",
    "GH_TOKEN_ENV_KEY",
    "ProxyEnvConfig",
    "ProxyEnvInput",
    "ProxyConfigService",
    "apply_proxy_env_to_process_env",
    "build_subprocess_env",
    "build_clawhub_cli_env",
    "build_clawhub_subprocess_env",
    "extract_proxy_env_vars",
    "build_github_cli_env",
    "clawhub_env_keys",
    "clear_clawhub_path_cache",
    "install_clawhub_via_npm",
    "get_app_env_file_path",
    "get_env_var",
    "get_project_env_file_path",
    "get_user_env_file_path",
    "github_env_keys",
    "host_matches_no_proxy",
    "load_proxy_env_config",
    "load_env_file",
    "load_merged_env_vars",
    "normalize_clawhub_site",
    "normalize_clawhub_token",
    "sync_app_env_to_process_env",
    "mask_proxy_url",
    "parse_no_proxy_rules",
    "proxy_applies_to_url",
    "resolve_proxy_env_config",
    "resolve_clawhub_registry_from_env",
    "resolve_clawhub_site_from_env",
    "resolve_default_clawhub_registry",
    "resolve_default_clawhub_site",
    "resolve_existing_clawhub_path",
    "resolve_clawhub_token_from_env",
    "strip_clawhub_endpoint_overrides",
    "normalize_github_token",
    "resolve_github_token_from_env",
    "sync_proxy_env_to_process_env",
    "WebConnectivityProbeDiagnostics",
    "WebConnectivityProbeRequest",
    "WebConnectivityProbeResult",
    "WebConnectivityProbeService",
    "WebConfig",
    "WebConfigService",
    "WebFallbackProvider",
    "WebProvider",
    "DEFAULT_CLAWHUB_CN_REGISTRY",
    "DEFAULT_CLAWHUB_CN_SITE",
    "normalize_clawhub_registry",
]
